serenity.project.name=qa-rest-screenplay-challenge
serenity.logging = VERBOSE
serenity.console.colors = true
serenity.dry.run=false
serenity.test.root=com.challenge.runners
serenity.reports.show.step.details = true
report.tagtypes=capability,feature
feature.file.encoding=UTF-8
serenity.report.encoding=UTF-8
serenity.encoding=UTF-8